apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: flux-system

spec:
  interval: 1h

  chart:
    spec:
      chart: renovate
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system

  targetNamespace: renovate

  install:
    createNamespace: true

  values:
    cronjob:
      schedule: "0 * * * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 5

    envFrom:
      - secretRef:
          name: renovate-env

    renovate:
      config: |
        {
          "platform": "github",
          "autodiscover": false,
          "repositories": [
            "Aishwaryaa12/k3s-flux"
          ],
          "onboarding": true,
          "requireConfig": "optional",
          "extends": [
            "config:recommended"
          ],
          "minimumReleaseAge": "48 hours"
        }

    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: "512Mi"
