apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: flux-system

spec:
  interval: 1h

  chart:
    spec:
      chart: renovate
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system

  targetNamespace: renovate

  install:
    createNamespace: true

  values:
    cronjob:
      schedule: "0 * * * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 5

    existingSecret: "renovate-env"
    envFrom:
      - secretRef:
          name: "renovate-env"

    extraEnv:
      - name: RENOVATE_TOKEN
        valueFrom:
          secretKeyRef:
            name: "renovate-env"
            key: "RENOVATE_TOKEN"


    renovate:
      platform: "github"
      logLevel: "info"
      autodiscover: true
      autodiscoverFilter: "Aishwaryaa12/*"
      config: |


        {
          "extends": ["config:recommended"],
          "onboarding": true,
          "requireConfig": "optional",
          "repositories": ["Aishwaryaa12/k3s-flux"],
          "minimumReleaseAge": "48 hours"


        }




    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: "512Mi"
