apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:WbKxXmTCMn6EcNS71pV2fkq9tgrEKMT7hAqH1fJbHb98ORMJS+gprS+N+BpVG076SjEEKDxjA7F88T6p8aH33U6uYUbGX2lpMPntnK9KGLW+L54COD4h1wc8pqK4,iv:PnkssjKhCpuAwnwGjT3cUfKxtHDMnTYOoyWq8tSK3tU=,tag:lCcdpDT6wwiAA8Wg4AYl3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdXUxUVUwYXVpUk9JL2k3
            T0VSNlVCdnNIK1ZGQ2dZSm9zWVVSNHRyT1FzCjNHRFlkYzduK1Y4M1JDZUZGRi8x
            TWNqRGM5TE10eXNSYlc3TEdxMDZaZ1UKLS0tIGlia2hvcTBQZlNIaUxHN3o4ckJD
            ZWI4M2xPOERlZG9kbzljVS9STVp1Y3cKFGbgHiASf8IbvRN2SZlNNrDT/WV/I043
            ElW7ZfrqivGhHhx5MPHyNnl80hgWJWDyOVS16pCyU87/0kSb1b7jXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7qx554qx2h7tlascwe4nlsp0lh04pr5dlzwrx23vhzp7jada4tqny07rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T14:28:02Z"
    mac: ENC[AES256_GCM,data:Efak8zv9xPwsERjcqjESu97y3FAmvodVUUDnjG0FIO9WS47+T0g3XwzX17ia+/hPc+cFXjW/NyI1OvXlnsMFH10WqHefRNUEMUHnoIMhUChvUglwfqdeWEZcOB9vaEpIMeigyIa2+gcn20bc9nazcKv07yT9jvTyU6ymRIJugfo=,iv:V+c8Br/Q2rsR6VCvJx8DOkXV3yTFVD+I2bi9heyOxDw=,tag:RffmV98M0Pume4bM4YFJxQ==,type:str]
    version: 3.13.3
