apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Nin3v7kJN6dfzx0lNeM3GJJOCP4IFB5wPrYDZDrTOxuiWsR5bL/kpxCVWo/6Nv9Qielj2HkPRTlEe/cS+v6LJ9S93Eq+y00ZLM3UgzD/OcNDU7KhjJ0NTmlsrbPN,iv:N+gKn0NbzwnfoFWmjyohPTQx+wa23qzppr0EaYACUY8=,tag:CjlA4YAspa8Yytj3E0Ds4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdXUxUVUwYXVpUk9JL2k3
            T0VSNlVCdnNIK1ZGQ2dZSm9zWVVSNHRyT1FzCjNHRFlkYzduK1Y4M1JDZUZGRi8x
            TWNqRGM5TE10eXNSYlc3TEdxMDZaZ1UKLS0tIGlia2hvcTBQZlNIaUxHN3o4ckJD
            ZWI4M2xPOERlZG9kbzljVS9STVp1Y3cKFGbgHiASf8IbvRN2SZlNNrDT/WV/I043
            ElW7ZfrqivGhHhx5MPHyNnl80hgWJWDyOVS16pCyU87/0kSb1b7jXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7qx554qx2h7tlascwe4nlsp0lh04pr5dlzwrx23vhzp7jada4tqny07rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T13:04:02Z"
    mac: ENC[AES256_GCM,data:60VfSchHWyymG7uzlJglrLAHz9clk994qdVdRtIQCexHxUof4VyzLIPJ6Nu7ph2rKeTcB6Mv+VCxgZmIpik0lhZhnflxr2k9D+xi+JUBUrrgmKysBVEWJ4IcM9sDky+afW0VehLdHL4xonhwcrshg6oICoU0+VROFiMZT9/yBUI=,iv:BDkQYkxf6FX9fb//ppYrztYMxP2SNgVDbiDuAji5aEI=,tag:X0gSMtVtoDEDM/Zk/2WqEQ==,type:str]
    version: 3.13.3
